name: Integración Continua

on:
  push:
    branches: [prod, dev]
  pull_request:
    branches: [prod, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
            cache: 'npm'
      - run: npm ci
      - run: npx prettier . --check
      - run: npm run lint
      - run: npm run test
      - run: npm run build 

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}